### ISSUE TITLE
about 'encode_hn2_rnn_100_2_full.mat'

### ISSUE THREAD

**Issue by zichihuanian** [jackyjsy/SCGAN#3]
hello author, thanks for your good job.
I can't find 'encode_hn2_rnn_100_2_full.mat' in Deepfashion Dataset, could you tell me what it is, thank you

**Comment by jackyjsy** [comment]
Dear Qinghe,

Thanks for pointing out! I think they stopped releasing this .mat file. Actually, we didn't use this .mat file after loading it. So you can simply comment out Line 109 in [data_loader.py](https://github.com/jackyjsy/SCGAN/blob/master/data_loader.py). I'll update the code to address this issue.

Songyao
